//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLiteTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLiteTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronous|OFF.
        /// </summary>
        internal static string PRAGMA_1 {
            get {
                return ResourceManager.GetString("PRAGMA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temp_store|MEMORY.
        /// </summary>
        internal static string PRAGMA_2 {
            get {
                return ResourceManager.GetString("PRAGMA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to journal_mode|MEMORY.
        /// </summary>
        internal static string PRAGMA_3 {
            get {
                return ResourceManager.GetString("PRAGMA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locking_mode|NORMAL.
        /// </summary>
        internal static string PRAGMA_4 {
            get {
                return ResourceManager.GetString("PRAGMA_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table1|Update|dbo.Table_1|Insert.
        /// </summary>
        internal static string TABLE_1 {
            get {
                return ResourceManager.GetString("TABLE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table2|Ignore|dbo.Table_2|Truncate.
        /// </summary>
        internal static string TABLE_2 {
            get {
                return ResourceManager.GetString("TABLE_2", resourceCulture);
            }
        }
    }
}
